# Generated by Django 3.1.4 on 2022-09-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilt', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
                ('dt_change', models.DateTimeField(auto_now=True)),
                ('html_template', models.FilePathField()),
            ],
        ),
    ]
