# Generated by Django 3.1.4 on 2022-09-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e0m', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Post_Model',
        ),
    ]
