# Generated by Django 3.1.4 on 2022-09-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e0m', '0002_auto_20220923_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_model',
            old_name='tilt',
            new_name='title',
        ),
    ]
