# Generated by Django 3.1.4 on 2022-09-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e0m', '0003_auto_20220923_1317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_Model',
            new_name='PostModel',
        ),
    ]
