# Generated by Django 3.1.4 on 2022-09-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e0m', '0004_auto_20220923_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='html_template',
            field=models.URLField(),
        ),
    ]
