# Generated by Django 3.1.4 on 2022-09-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e0m', '0005_auto_20220923_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='html_template',
        ),
    ]
